#pragma once
// "Gemma4Synth v1" in C++: the synthetic Gemma 4 checkpoint of
// tools/gemma4_synth.py, regenerated byte for byte from (tensor name, seed)
// and the family's tensor table, and written as config.json +
// model.safetensors into a directory. The content rule is the Python
// file's docstring; the unit test proves the two generators agree by the
// content hash the Python tool recorded (gemma4_reference_vectors.hpp).
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <map>
#include <stdexcept>
#include <string>
#include <vector>

#include "common/dtypes.hpp"
#include "models/gemma4/binding.hpp"
#include "models/gemma4/config.hpp"

namespace gemma4_synth {

inline uint64_t fnv1a64(const std::string& s) {
  uint64_t h = 1469598103934665603ull;
  for (const char c : s) h = (h ^ static_cast<uint8_t>(c)) * 1099511628211ull;
  return h;
}

// stream(name, seed)[k], k from 0.
struct Stream {
  uint64_t base;
  Stream(const std::string& name, uint64_t seed) : base(fnv1a64(name) ^ seed) {}
  uint64_t at(uint64_t k) const {
    uint64_t z = base + (k + 1) * 0x9E3779B97F4A7C15ull;
    z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ull;
    z = (z ^ (z >> 27)) * 0x94D049BB133111EBull;
    return z ^ (z >> 31);
  }
  // float32 in [-1, 1), exact (24 bits).
  float uniform(uint64_t k) const { return static_cast<float>(at(k) >> 40) / 8388608.0f - 1.0f; }
};

struct SynthTensor {
  dgpp::DType dtype{};
  std::vector<int64_t> shape;
  std::vector<uint8_t> bytes;
};

enum class Bf16Kind { Matrix, Embed, Norm, Scalar, Router };

inline std::vector<uint8_t> bf16_bytes(const std::string& name, uint64_t seed, size_t n, Bf16Kind kind) {
  const Stream s(name, seed);
  std::vector<uint8_t> out(n * 2);
  for (size_t k = 0; k < n; ++k) {
    const float u = s.uniform(k);
    float x = 0.0f;
    switch (kind) {
      case Bf16Kind::Matrix: x = u * 0.25f; break;
      case Bf16Kind::Embed: x = u * 0.5f; break;
      case Bf16Kind::Norm: x = 1.0f + 0.25f * u; break;
      case Bf16Kind::Scalar: x = 0.875f + 0.125f * u; break;
      case Bf16Kind::Router: x = u * 4.0f; break;
    }
    const uint16_t b = dgpp::float_to_bf16_bits(x);
    std::memcpy(out.data() + 2 * k, &b, 2);
  }
  return out;
}

// name -> tensor for the checkpoint `cfg` describes (sorted by name: the
// content hash's order), plus the one encoder tensor the Python tool adds.
inline std::map<std::string, SynthTensor> tensors(const dgpp::Gemma4TextConfig& cfg, uint64_t seed) {
  std::map<std::string, SynthTensor> out;
  for (const dgpp::Gemma4ExpectedTensor& e : dgpp::gemma4_expected_text_tensors(cfg)) {
    SynthTensor t;
    t.dtype = e.dtype;
    t.shape = e.shape;
    const size_t n = e.numel();
    switch (e.role) {
      case dgpp::Gemma4TensorRole::Plain: {
        Bf16Kind kind = Bf16Kind::Matrix;
        if (e.cls == dgpp::Gemma4WeightClass::Embed) kind = Bf16Kind::Embed;
        else if (e.cls == dgpp::Gemma4WeightClass::LayerScalar) kind = Bf16Kind::Scalar;
        else if (e.shape.size() == 1) kind = Bf16Kind::Norm;
        else if (e.cls == dgpp::Gemma4WeightClass::Router) kind = Bf16Kind::Router;  // router.proj
        if (e.dtype != dgpp::DType::BF16) throw std::logic_error("gemma4_synth: a plain tensor that is not BF16");
        t.bytes = bf16_bytes(e.name, seed, n, kind);
        break;
      }
      case dgpp::Gemma4TensorRole::Fp4Payload: {
        const Stream s(e.name, seed);
        t.bytes.resize(n);
        for (size_t k = 0; k < n; ++k) t.bytes[k] = static_cast<uint8_t>(s.at(k) >> 56);
        break;
      }
      case dgpp::Gemma4TensorRole::Fp4Scale: {
        const Stream s(e.name, seed);
        t.bytes.resize(n);
        for (size_t k = 0; k < n; ++k) t.bytes[k] = static_cast<uint8_t>(0x38u + (s.at(k) >> 60));
        break;
      }
      case dgpp::Gemma4TensorRole::Fp4Global: {
        const Stream s(e.name, seed);
        const float ws2 = static_cast<float>(1 + (s.at(0) >> 60)) / 256.0f;
        t.bytes.resize(4);
        std::memcpy(t.bytes.data(), &ws2, 4);
        break;
      }
      case dgpp::Gemma4TensorRole::InputScale: {
        const float one = 1.0f;
        t.bytes.resize(4);
        std::memcpy(t.bytes.data(), &one, 4);
        break;
      }
    }
    out.emplace(e.name, std::move(t));
  }
  SynthTensor enc;
  enc.dtype = dgpp::DType::BF16;
  enc.shape = {8};
  enc.bytes = bf16_bytes("model.vision_tower.std_bias", seed, 8, Bf16Kind::Norm);
  out.emplace("model.vision_tower.std_bias", std::move(enc));
  return out;
}

// FNV-1a-64 over every tensor's bytes, tensors in name order.
inline uint64_t content_hash(const std::map<std::string, SynthTensor>& ts) {
  uint64_t h = 1469598103934665603ull;
  for (const auto& [name, t] : ts)
    for (const uint8_t b : t.bytes) h = (h ^ b) * 1099511628211ull;
  return h;
}

// Writes `ts` as one safetensors file (the header padded to 8 bytes).
inline void write_safetensors(const std::filesystem::path& path, const std::map<std::string, SynthTensor>& ts) {
  std::string header = "{";
  uint64_t off = 0;
  for (const auto& [name, t] : ts) {
    header += "\"" + name + "\":{\"dtype\":\"" + std::string(dgpp::dtype_name(t.dtype)) + "\",\"shape\":[";
    for (size_t i = 0; i < t.shape.size(); ++i) header += (i ? "," : "") + std::to_string(t.shape[i]);
    header += "],\"data_offsets\":[" + std::to_string(off) + "," + std::to_string(off + t.bytes.size()) + "]},";
    off += t.bytes.size();
  }
  header += "\"__metadata__\":{\"format\":\"pt\"}}";
  while (header.size() % 8 != 0) header += ' ';
  std::FILE* f = std::fopen(path.c_str(), "wb");
  if (!f) throw std::runtime_error("gemma4_synth: cannot write " + path.string());
  const uint64_t hlen = header.size();
  std::fwrite(&hlen, 8, 1, f);
  std::fwrite(header.data(), 1, header.size(), f);
  for (const auto& [name, t] : ts) std::fwrite(t.bytes.data(), 1, t.bytes.size(), f);
  std::fclose(f);
}

// config.json (the text the Python tool wrote) + model.safetensors in `dir`.
inline void write_checkpoint(const std::filesystem::path& dir, const char* config_json,
                             const std::map<std::string, SynthTensor>& ts) {
  std::filesystem::create_directories(dir);
  std::FILE* f = std::fopen((dir / "config.json").c_str(), "wb");
  if (!f) throw std::runtime_error("gemma4_synth: cannot write config.json in " + dir.string());
  std::fwrite(config_json, 1, std::strlen(config_json), f);
  std::fclose(f);
  write_safetensors(dir / "model.safetensors", ts);
}

}  // namespace gemma4_synth
