// The MiniMax-M2 host references against tools/minimax_m2_reference.py on a
// synthetic checkpoint (tests/unit/minimax_attn_vectors.hpp, generated by
// tools/minimax_m2_synth.py vectors): the attention layer with its
// per-layer q/k norm stage by stage, the same layer split over two ranks
// the way docs/minimax_m27_plan.md shards it, the sigmoid router and the
// whole MoE block through the engine's existing oracle on the layer's
// NVFP4 containers.
//
// The python reference computes in float64 without rounding; the host
// references round to bf16 where the device does. The bounds are a few
// bf16 ulps of the tensor's scale; the per-head norm (GLM-4.7's, what the
// engine's existing qkv finish computes) misses them by an order of
// magnitude.
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <iterator>
#include <stdexcept>
#include <string>
#include <vector>

#include "common/dtypes.hpp"
#include "common/test.hpp"
#include "minimax_attn_vectors.hpp"
#include "models/glm/moe_reference.hpp"
#include "models/glm4/attn_reference.hpp"
#include "models/minimax/attn_reference.hpp"
#include "models/minimax/config.hpp"

namespace {

namespace v = minimax_vectors;
using dgpp::bf16_bits_to_float;
using dgpp::float_to_bf16_bits;
using dgpp::minimax_ref::Geometry;
using dgpp::minimax_ref::HostState;
using dgpp::minimax_ref::HostWeights;
using dgpp::minimax_ref::Taps;

void require(bool cond, const std::string& what) {
  if (!cond) throw std::runtime_error(what);
}

// The synthetic checkpoint's config.json, as the parsed struct.
dgpp::MinimaxTextConfig config() {
  dgpp::MinimaxTextConfig c;
  c.hidden_size = v::kHidden;
  c.num_attention_heads = v::kHeads;
  c.num_key_value_heads = v::kKvHeads;
  c.head_dim = v::kHeadDim;
  c.rotary_dim = v::kRotaryDim;
  c.rope_theta = v::kTheta;
  c.rms_norm_eps = v::kEps;
  c.moe_intermediate_size = v::kInter;
  c.n_routed_experts = v::kExperts;
  c.num_experts_per_tok = v::kTopK;
  return c;
}

// max |got - want| over the tensor, relative to max |want|.
template <typename Get>
double rel_error_of(Get get, const double* want, size_t n) {
  double worst = 0.0, scale = 0.0;
  for (size_t i = 0; i < n; ++i) {
    worst = std::max(worst, std::fabs(static_cast<double>(get(i)) - want[i]));
    scale = std::max(scale, std::fabs(want[i]));
  }
  return scale > 0 ? worst / scale : worst;
}
double rel_error(const std::vector<uint16_t>& got, const double* want) {
  return rel_error_of([&](size_t i) { return bf16_bits_to_float(got[i]); }, want, got.size());
}

// The rank's views of the layer: q_proj / k_proj and the norms whole,
// v_proj rows and o_proj columns sliced.
struct RankWeights {
  std::vector<uint16_t> v_proj, o_proj;
  HostWeights view;
};
RankWeights rank_weights(const Geometry& g) {
  RankWeights r;
  const int d = g.dim, H = g.hidden;
  r.v_proj.assign(v::k_v_proj + static_cast<size_t>(g.kv_begin) * d * H,
                  v::k_v_proj + static_cast<size_t>(g.kv_begin + g.local_kv) * d * H);
  r.o_proj.resize(static_cast<size_t>(H) * g.local_heads * d);
  for (int row = 0; row < H; ++row)
    std::copy(v::k_o_proj + static_cast<size_t>(row) * g.q_width() +
                  static_cast<size_t>(g.head_begin) * d,
              v::k_o_proj + static_cast<size_t>(row) * g.q_width() +
                  static_cast<size_t>(g.head_begin + g.local_heads) * d,
              r.o_proj.begin() + static_cast<int64_t>(row) * g.local_heads * d);
  r.view.q_proj = v::k_q_proj;
  r.view.k_proj = v::k_k_proj;
  r.view.q_norm = v::k_q_norm;
  r.view.k_norm = v::k_k_norm;
  r.view.v_proj = r.v_proj.data();
  r.view.o_proj = r.o_proj.data();
  return r;
}

struct RankRun {
  std::vector<float> out;  // [tokens, hidden] fp32 (a partial sum past world 1)
  Taps taps;
  HostState state;
};
RankRun run_rank(const dgpp::MinimaxTextConfig& cfg, int rank, int world) {
  const Geometry g = Geometry::from_config(cfg, rank, world);
  const RankWeights w = rank_weights(g);
  const std::vector<float> inv_freq = cfg.rope_inv_freq();
  RankRun r;
  r.state.reset(v::kPos0);
  r.out.assign(static_cast<size_t>(v::kTokens) * v::kHidden, 0.f);
  // Fed in two pieces: the K/V rows carry over.
  const int first = v::kTokens / 3;
  dgpp::minimax_ref::layer_forward(w.view, g, inv_freq.data(), v::k_hidden, r.state, first,
                                   r.out.data(), &r.taps);
  Taps rest;
  dgpp::minimax_ref::layer_forward(w.view, g, inv_freq.data(), v::k_hidden + first * v::kHidden,
                                   r.state, v::kTokens - first,
                                   r.out.data() + static_cast<size_t>(first) * v::kHidden, &rest);
  r.taps.q.insert(r.taps.q.end(), rest.q.begin(), rest.q.end());
  r.taps.k.insert(r.taps.k.end(), rest.k.begin(), rest.k.end());
  r.taps.v.insert(r.taps.v.end(), rest.v.begin(), rest.v.end());
  r.taps.heads.insert(r.taps.heads.end(), rest.heads.begin(), rest.heads.end());
  return r;
}

// Measured on these vectors: 0.003 - 0.008 at every stage.
constexpr double kStageBound = 0.015;

}  // namespace

DGPP_TEST(minimax_rope_inv_freq_matches_the_reference) {
  const std::vector<float> f = config().rope_inv_freq();
  require(f.size() == static_cast<size_t>(v::kRotaryDim / 2), "lanes");
  for (size_t i = 0; i < f.size(); ++i)
    require(std::fabs(f[i] - v::k_inv_freq[i]) <= 2e-7f * v::k_inv_freq[i],
            "inv_freq lane " + std::to_string(i));
}

DGPP_TEST(minimax_attention_layer_matches_the_numpy_reference) {
  const dgpp::MinimaxTextConfig cfg = config();
  const RankRun r = run_rank(cfg, 0, 1);
  require(r.state.num_tokens == v::kTokens, "the K/V rows hold every token");
  const double eq = rel_error(r.taps.q, v::k_ref_q), ek = rel_error(r.taps.k, v::k_ref_k);
  const double ev = rel_error(r.taps.v, v::k_ref_v),
               eh = rel_error(r.taps.heads, v::k_ref_attn_heads);
  const double eo = rel_error_of([&](size_t i) { return r.out[i]; }, v::k_ref_out, r.out.size());
  std::printf("  layer: q %.4f k %.4f v %.4f heads %.4f out %.4f\n", eq, ek, ev, eh, eo);
  require(eq < kStageBound && ek < kStageBound && ev < kStageBound, "projections and norm");
  require(eh < kStageBound && eo < kStageBound, "attention output");
  // The same q rows against the per-head reading of the same weights: a different function.
  const double wrong = rel_error(r.taps.q, v::k_ref_q_per_head);
  std::printf("  the per-layer q against the per-head reference: %.4f\n", wrong);
  require(wrong > 4 * kStageBound,
          "per-layer and per-head norms are not told apart: " + std::to_string(wrong));
}

DGPP_TEST(minimax_per_head_finish_is_not_this_models_norm) {
  // GLM-4.7's finish (models/glm4/attn_reference.hpp: an RMS per head, one
  // [dim] weight) applied head by head with each head's slice of q_norm:
  // what reusing the existing qkv finish kernel unchanged would compute.
  const dgpp::MinimaxTextConfig cfg = config();
  const Geometry g = Geometry::from_config(cfg);
  const std::vector<float> inv_freq = cfg.rope_inv_freq();
  std::vector<float> dot(static_cast<size_t>(g.q_width()));
  std::vector<uint16_t> per_head(static_cast<size_t>(v::kTokens) * g.q_width());
  for (int t = 0; t < v::kTokens; ++t) {
    for (int n = 0; n < g.q_width(); ++n) {
      float acc = 0.f;
      for (int k = 0; k < g.hidden; ++k)
        acc = std::fma(bf16_bits_to_float(v::k_hidden[t * g.hidden + k]),
                       bf16_bits_to_float(v::k_q_proj[static_cast<size_t>(n) * g.hidden + k]), acc);
      dot[static_cast<size_t>(n)] = acc;
    }
    for (int h = 0; h < g.heads; ++h)
      dgpp::glm4_ref::qkv_finish(dot.data() + h * g.dim, nullptr, v::k_q_norm + h * g.dim, g.eps,
                                 inv_freq.data(), g.rotary_dim, v::kPos0 + t,
                                 per_head.data() + (static_cast<size_t>(t) * g.heads + h) * g.dim,
                                 g.dim);
  }
  const double as_per_head = rel_error(per_head, v::k_ref_q_per_head);
  const double as_per_layer = rel_error(per_head, v::k_ref_q);
  std::printf("  glm4 finish: against the per-head reference %.4f, against this model's %.4f\n",
              as_per_head, as_per_layer);
  require(as_per_head < kStageBound, "the glm4 finish is the per-head norm");
  require(as_per_layer > 4 * kStageBound, "and it is not this model's");
}

DGPP_TEST(minimax_two_rank_shards_sum_to_the_single_rank_layer) {
  // The plan's sharding at host level: each rank norms the whole q / k row
  // and keeps its heads; its K/V rows are the single rank's slice bit for
  // bit; the two o_proj partial sums add up to the single rank's output.
  const dgpp::MinimaxTextConfig cfg = config();
  const RankRun one = run_rank(cfg, 0, 1);
  const RankRun r0 = run_rank(cfg, 0, 2), r1 = run_rank(cfg, 1, 2);
  const int d = v::kHeadDim, lq = v::kHeads / 2 * d, lk = v::kKvHeads / 2 * d;
  for (int t = 0; t < v::kTokens; ++t) {
    require(std::equal(r0.taps.q.begin() + t * lq, r0.taps.q.begin() + (t + 1) * lq,
                       one.taps.q.begin() + t * 2 * lq),
            "rank 0's query heads are the first half, bitwise");
    require(std::equal(r1.taps.q.begin() + t * lq, r1.taps.q.begin() + (t + 1) * lq,
                       one.taps.q.begin() + t * 2 * lq + lq),
            "rank 1's query heads are the second half, bitwise");
    require(std::equal(r0.state.k.begin() + t * lk, r0.state.k.begin() + (t + 1) * lk,
                       one.state.k.begin() + t * 2 * lk) &&
                std::equal(r1.state.k.begin() + t * lk, r1.state.k.begin() + (t + 1) * lk,
                           one.state.k.begin() + t * 2 * lk + lk),
            "the K rows split by kv head, bitwise");
    require(std::equal(r0.state.v.begin() + t * lk, r0.state.v.begin() + (t + 1) * lk,
                       one.state.v.begin() + t * 2 * lk) &&
                std::equal(r1.state.v.begin() + t * lk, r1.state.v.begin() + (t + 1) * lk,
                           one.state.v.begin() + t * 2 * lk + lk),
            "the V rows split by kv head, bitwise");
    require(std::equal(r0.taps.heads.begin() + t * lq, r0.taps.heads.begin() + (t + 1) * lq,
                       one.taps.heads.begin() + t * 2 * lq) &&
                std::equal(r1.taps.heads.begin() + t * lq, r1.taps.heads.begin() + (t + 1) * lq,
                           one.taps.heads.begin() + t * 2 * lq + lq),
            "the heads' attention output, bitwise");
  }
  double worst = 0.0, scale = 0.0;
  for (size_t i = 0; i < one.out.size(); ++i) {
    worst = std::max(worst, static_cast<double>(std::fabs(r0.out[i] + r1.out[i] - one.out[i])));
    scale = std::max(scale, static_cast<double>(std::fabs(one.out[i])));
  }
  std::printf("  o_proj partial sums: max |rank0 + rank1 - world1| = %.3g of scale %.3g\n", worst,
              scale);
  require(worst < 1e-5 * scale, "the partial sums add up (fp32 association only)");
  // And the folded output, rounded once, is the reference's.
  std::vector<uint16_t> folded(one.out.size());
  for (size_t i = 0; i < folded.size(); ++i) folded[i] = float_to_bf16_bits(r0.out[i] + r1.out[i]);
  require(rel_error(folded, v::k_ref_out) < kStageBound,
          "the folded output against the numpy reference");
}

DGPP_TEST(minimax_router_is_the_sigmoid_bias_oracle) {
  const dgpp::GlmMoeConfig mc = config().moe_config(v::kInter);
  // The checkpoint's bias is BF16; the engine's router takes F32.
  std::vector<float> bias(static_cast<size_t>(v::kExperts));
  for (int e = 0; e < v::kExperts; ++e)
    bias[static_cast<size_t>(e)] = bf16_bits_to_float(v::k_router_bias[e]);
  dgpp::GlmMoeRouterRef route;
  dgpp::glm_moe_ref_router(v::k_hidden, v::k_gate, bias.data(), mc, v::kTokens, route);
  double worst = 0.0;
  for (int t = 0; t < v::kTokens; ++t)
    for (int k = 0; k < v::kTopK; ++k) {
      const size_t i = static_cast<size_t>(t) * v::kTopK + k;
      require(route.ids[i] == v::k_route_ids[i], "token " + std::to_string(t) + ": expert " +
                                                     std::to_string(route.ids[i]) +
                                                     " != " + std::to_string(v::k_route_ids[i]));
      worst = std::max(worst, std::fabs(static_cast<double>(route.weights[i]) - v::k_route_w[i]));
    }
  std::printf("  router: %d tokens, max weight error %.2e\n", v::kTokens, worst);
  require(worst < 1e-5, "router weights: " + std::to_string(worst));
  // Without the bias the picks differ somewhere (the bias is live in these vectors).
  std::vector<float> zero(static_cast<size_t>(v::kExperts), 0.f);
  dgpp::GlmMoeRouterRef unbiased;
  dgpp::glm_moe_ref_router(v::k_hidden, v::k_gate, zero.data(), mc, v::kTokens, unbiased);
  require(unbiased.ids != route.ids, "the correction bias changes a pick");
}

DGPP_TEST(minimax_moe_block_is_the_engines_nvfp4_oracle) {
  // The existing MoE oracle on this layer's containers: w1 / w3 / w2 as
  // gate / up / down, no shared expert, 1 / weight_scale_2 as the divisor.
  const dgpp::GlmMoeConfig mc = config().moe_config(v::kInter);
  dgpp::GlmMoeHostWeights w;
  w.router_gate.assign(v::k_gate, v::k_gate + static_cast<size_t>(v::kExperts) * v::kHidden);
  w.router_bias.resize(static_cast<size_t>(v::kExperts));
  for (int e = 0; e < v::kExperts; ++e)
    w.router_bias[static_cast<size_t>(e)] = bf16_bits_to_float(v::k_router_bias[e]);
  w.nvfp4 = true;
  w.shared_nvfp4 = false;
  w.fp4_group = 16;
  w.fp4_payloads.assign(std::begin(v::k_fp4_payloads), std::end(v::k_fp4_payloads));
  w.fp4_scales.assign(std::begin(v::k_fp4_scales), std::end(v::k_fp4_scales));
  w.fp4_globals.assign(std::begin(v::k_fp4_divisors), std::end(v::k_fp4_divisors));
  require(w.fp4_globals.size() == static_cast<size_t>(v::kExperts) * 3, "one divisor per matrix");
  std::vector<uint16_t> out;
  dgpp::glm_moe_ref_forward(v::k_hidden, w, mc, v::kTokens, out);
  require(out.size() == static_cast<size_t>(v::kTokens) * v::kHidden, "output rows");
  const double e = rel_error(out, v::k_moe_out);
  std::printf("  moe block: out error %.4f\n", e);
  require(e < kStageBound, "moe block: " + std::to_string(e));
  // weight_scale_2 used as the divisor itself (the compressed-tensors convention) is far off.
  dgpp::GlmMoeHostWeights wrong = w;
  for (float& g : wrong.fp4_globals) g = 1.0f / g;
  std::vector<uint16_t> out2;
  dgpp::glm_moe_ref_forward(v::k_hidden, wrong, mc, v::kTokens, out2);
  const double e2 = rel_error(out2, v::k_moe_out);
  std::printf("  moe block with weight_scale_2 as the divisor: out error %.3g\n", e2);
  require(!(e2 < 4 * kStageBound), "the multiplier / divisor convention is not told apart");
}
