// The Mistral-Small-4 host references against tools/mistral4_reference.py on
// a synthetic checkpoint (tests/unit/mistral4_mla_vectors.hpp, generated by
// tools/mistral4_synth.py vectors): the YaRN table and the Llama-4 scale,
// the attention layer stage by stage at two position runs (from 0, and
// across the Llama-4 step into the YaRN-interpolated range), the softmax
// router and the whole MoE block through the engine's existing oracle on
// the layer's NVFP4 containers.
//
// The python reference computes in float64 without rounding; the host
// references round to bf16 where the device does. The bounds below are a
// few bf16 ulps of the tensor's scale — the last test shows what a wrong
// convention costs against them.
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <iterator>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include "common/dtypes.hpp"
#include "common/test.hpp"
#include "mistral4_mla_vectors.hpp"
#include "models/glm/moe_reference.hpp"
#include "models/mistral4/config.hpp"
#include "models/mistral4/mla_reference.hpp"

namespace {

namespace v = mistral4_vectors;
using dgpp::bf16_bits_to_float;
using dgpp::mistral4_ref::Geometry;
using dgpp::mistral4_ref::HostState;
using dgpp::mistral4_ref::HostWeights;
using dgpp::mistral4_ref::Taps;

void require(bool cond, const std::string& what) {
  if (!cond) throw std::runtime_error(what);
}

// The synthetic checkpoint's params.json, as the parsed struct.
dgpp::Mistral4TextConfig config() {
  dgpp::Mistral4TextConfig c;
  c.hidden_size = v::kHidden;
  c.num_attention_heads = v::kHeads;
  c.q_lora_rank = v::kQLora;
  c.kv_lora_rank = v::kKvLora;
  c.qk_nope_head_dim = v::kNope;
  c.qk_rope_head_dim = v::kRope;
  c.v_head_dim = v::kV;
  c.rms_norm_eps = v::kEps;
  c.rope_theta = v::kTheta;
  c.yarn_factor = v::kYarnFactor;
  c.yarn_original_max_position_embeddings = v::kYarnOriginal;
  c.yarn_beta_fast = v::kYarnBetaFast;
  c.yarn_beta_slow = v::kYarnBetaSlow;
  c.llama4_scaling_beta = v::kLlama4Beta;
  c.llama4_original_max_position_embeddings = v::kLlama4Original;
  c.moe_intermediate_size = v::kInter;
  c.n_routed_experts = v::kExperts;
  c.num_experts_per_tok = v::kTopK;
  c.n_shared_experts = 1;
  return c;
}

HostWeights weights() {
  HostWeights w;
  w.wq_a = v::k_wq_a;
  w.q_a_norm = v::k_q_a_norm;
  w.wq_b = v::k_wq_b;
  w.wkv_a = v::k_wkv_a_with_mqa;
  w.kv_a_norm = v::k_kv_a_norm;
  w.wkv_b = v::k_wkv_b;
  w.wo = v::k_wo;
  return w;
}

// max |got - want| over the tensor, relative to max |want|.
double rel_error(const uint16_t* got, const double* want, size_t n) {
  double worst = 0.0, scale = 0.0;
  for (size_t i = 0; i < n; ++i) {
    worst = std::max(worst, std::fabs(static_cast<double>(bf16_bits_to_float(got[i])) - want[i]));
    scale = std::max(scale, std::fabs(want[i]));
  }
  return scale > 0 ? worst / scale : worst;
}

struct RunVectors {
  const double* llama4;
  const double* latent;
  const double* k_rope;
  const double* q;
  const double* heads;
  const double* out;
};
RunVectors run_vectors(int r) {
  if (r == 0)
    return {v::k_run0_llama4, v::k_run0_latent,     v::k_run0_k_rope,
            v::k_run0_q,      v::k_run0_attn_heads, v::k_run0_out};
  return {v::k_run1_llama4, v::k_run1_latent,     v::k_run1_k_rope,
          v::k_run1_q,      v::k_run1_attn_heads, v::k_run1_out};
}

struct LayerError {
  double latent = 0, k_rope = 0, q = 0, heads = 0, out = 0;
  double worst() const { return std::max({latent, k_rope, q, heads, out}); }
};

template <typename Acc>
LayerError run_layer(int r, const Geometry& g, const std::vector<float>& inv_freq) {
  const RunVectors want = run_vectors(r);
  HostState st;
  st.reset(v::kRunPos0[r]);
  Taps taps;
  std::vector<uint16_t> out(static_cast<size_t>(v::kTokens) * v::kHidden);
  // Fed in two pieces: the cache carries over.
  const int first = v::kTokens / 3;
  dgpp::mistral4_ref::layer_forward<Acc>(weights(), g, inv_freq.data(), v::k_hidden, st, first,
                                         out.data(), &taps);
  Taps rest;
  dgpp::mistral4_ref::layer_forward<Acc>(
      weights(), g, inv_freq.data(), v::k_hidden + first * v::kHidden, st, v::kTokens - first,
      out.data() + static_cast<size_t>(first) * v::kHidden, &rest);
  taps.q.insert(taps.q.end(), rest.q.begin(), rest.q.end());
  taps.latent.insert(taps.latent.end(), rest.latent.begin(), rest.latent.end());
  taps.k_rope.insert(taps.k_rope.end(), rest.k_rope.begin(), rest.k_rope.end());
  taps.heads.insert(taps.heads.end(), rest.heads.begin(), rest.heads.end());
  require(st.num_tokens == v::kTokens, "the cache holds every token");
  LayerError e;
  e.latent = rel_error(taps.latent.data(), want.latent, taps.latent.size());
  e.k_rope = rel_error(taps.k_rope.data(), want.k_rope, taps.k_rope.size());
  e.q = rel_error(taps.q.data(), want.q, taps.q.size());
  e.heads = rel_error(taps.heads.data(), want.heads, taps.heads.size());
  e.out = rel_error(out.data(), want.out, out.size());
  return e;
}

std::string describe(const LayerError& e) {
  char buf[160];
  std::snprintf(buf, sizeof buf, "latent %.4f k_rope %.4f q %.4f heads %.4f out %.4f", e.latent,
                e.k_rope, e.q, e.heads, e.out);
  return buf;
}

// bf16 keeps 8 significant bits (half an ulp is 2^-9 of a value's own
// magnitude); a stage is a handful of such roundings. Measured on these
// vectors: 0.004 - 0.010 at every stage, in float and in double.
constexpr double kStageBound = 0.01;    // the latents, the rope key, the query
constexpr double kOutputBound = 0.015;  // the heads' output and the layer's, after the softmax

}  // namespace

DGPP_TEST(mistral4_mla_rope_and_llama4_match_the_reference) {
  const dgpp::Mistral4TextConfig cfg = config();
  const std::vector<float> inv_freq = cfg.rope_inv_freq();
  require(inv_freq.size() == static_cast<size_t>(v::kRope / 2), "lanes");
  // The engine's YaRN builder and the python one: the same fp32 numbers.
  int kept = 0, divided = 0;
  for (int i = 0; i < v::kRope / 2; ++i) {
    char msg[96];
    std::snprintf(msg, sizeof msg, "inv_freq[%d]: %a != %a", i,
                  static_cast<double>(inv_freq[size_t(i)]), static_cast<double>(v::k_inv_freq[i]));
    require(inv_freq[size_t(i)] == v::k_inv_freq[i], msg);
    const float plain = 1.0f / static_cast<float>(std::pow(
                                   v::kTheta, static_cast<double>(float(2 * i) / float(v::kRope))));
    kept += inv_freq[size_t(i)] == plain;
    divided += inv_freq[size_t(i)] == plain / static_cast<float>(v::kYarnFactor);
  }
  require(kept >= 1 && divided >= 1 && kept + divided < v::kRope / 2,
          "the band has kept, blended and interpolated lanes");
  // The Llama-4 scale: one run stays below the step, the other crosses it.
  const Geometry g = Geometry::from_config(cfg);
  bool crossed = false;
  for (int r = 0; r < v::kRuns; ++r)
    for (int t = 0; t < v::kTokens; ++t) {
      const int64_t pos = v::kRunPos0[r] + t;
      const float s = dgpp::mistral4_ref::llama4_scale(g.llama4_beta, g.llama4_original, pos);
      require(std::fabs(static_cast<double>(s) - run_vectors(r).llama4[t]) < 2e-7,
              "llama4 scale at " + std::to_string(pos));
      require(s == cfg.llama4_query_scale(pos), "the config's helper is the reference's");
      crossed = crossed || s != 1.0f;
    }
  require(crossed, "the second run crosses the Llama-4 step");
  // The table is the row function, position by position.
  std::vector<uint16_t> table(static_cast<size_t>(4) * v::kRope),
      row(static_cast<size_t>(v::kRope));
  dgpp::mistral4_ref::rope_table(inv_freq.data(), v::kRope, 4, table.data());
  for (int p = 0; p < 4; ++p) {
    dgpp::mistral4_ref::rope_row(inv_freq.data(), v::kRope, p, row.data());
    require(std::equal(row.begin(), row.end(), table.begin() + p * v::kRope),
            "table row " + std::to_string(p));
  }
  require(table[0] == dgpp::float_to_bf16_bits(1.0f) && table[size_t(v::kRope / 2)] == 0,
          "position 0 is the identity");
}

DGPP_TEST(mistral4_mla_layer_matches_the_numpy_reference) {
  const dgpp::Mistral4TextConfig cfg = config();
  const Geometry g = Geometry::from_config(cfg);
  const std::vector<float> inv_freq = cfg.rope_inv_freq();
  for (int r = 0; r < v::kRuns; ++r) {
    const LayerError d = run_layer<double>(r, g, inv_freq);
    const LayerError f = run_layer<float>(r, g, inv_freq);
    std::printf("  run %d (pos0 %lld): double %s | float %s\n", r, v::kRunPos0[r],
                describe(d).c_str(), describe(f).c_str());
    for (const LayerError* e : {&d, &f}) {
      require(e->latent < kStageBound && e->k_rope < kStageBound && e->q < kStageBound,
              "run " + std::to_string(r) + " stages: " + describe(*e));
      require(e->heads < kOutputBound && e->out < kOutputBound,
              "run " + std::to_string(r) + " output: " + describe(*e));
    }
  }
}

DGPP_TEST(mistral4_mla_wrong_conventions_are_visible) {
  // Each wrong reading must miss the reference by far more than the bound a
  // right one meets; otherwise the test above could not tell them apart.
  const dgpp::Mistral4TextConfig cfg = config();
  const Geometry g = Geometry::from_config(cfg);
  const std::vector<float> inv_freq = cfg.rope_inv_freq();
  const int run = 1;  // across a Llama-4 step, in the YaRN-interpolated range
  const LayerError right = run_layer<double>(run, g, inv_freq);
  struct Case {
    const char* name;
    LayerError e;
  };
  std::vector<Case> cases;
  {
    // transformers main's softmax scale: * (0.1 ln factor + 1)^2.
    Geometry w = g;
    const float m = 0.1f * std::log(static_cast<float>(v::kYarnFactor)) + 1.0f;
    w.scale = g.scale * m * m;
    cases.push_back({"yarn mscale on the softmax scale", run_layer<double>(run, w, inv_freq)});
  }
  {
    Geometry w = g;
    w.llama4_beta = 0.0f;
    cases.push_back({"no Llama-4 scale", run_layer<double>(run, w, inv_freq)});
  }
  {
    // The plain rope (no YaRN blend).
    std::vector<float> plain(inv_freq.size());
    for (size_t i = 0; i < plain.size(); ++i)
      plain[i] = 1.0f / static_cast<float>(std::pow(
                            v::kTheta, static_cast<double>(float(2 * i) / float(v::kRope))));
    cases.push_back({"unblended rope frequencies", run_layer<double>(run, g, plain)});
  }
  for (const Case& c : cases) {
    std::printf("  %-34s %s\n", c.name, describe(c.e).c_str());
    require(c.e.worst() > 4 * kOutputBound,
            std::string(c.name) + " is not told apart: " + describe(c.e));
  }
  std::printf("  %-34s %s\n", "the right reading", describe(right).c_str());
  require(right.worst() < kOutputBound, "the right reading meets the bound");
}

DGPP_TEST(mistral4_router_is_the_softmax_topk_oracle) {
  const dgpp::GlmMoeConfig mc = config().moe_config(v::kInter);
  dgpp::GlmMoeRouterRef route;
  dgpp::glm_moe_ref_router(v::k_hidden, v::k_gate, nullptr, mc, v::kTokens, route);
  require(route.ids.size() == static_cast<size_t>(v::kTokens) * v::kTopK, "ids");
  double worst = 0.0;
  for (int t = 0; t < v::kTokens; ++t)
    for (int k = 0; k < v::kTopK; ++k) {
      const size_t i = static_cast<size_t>(t) * v::kTopK + k;
      require(route.ids[i] == v::k_route_ids[i], "token " + std::to_string(t) + ": expert " +
                                                     std::to_string(route.ids[i]) +
                                                     " != " + std::to_string(v::k_route_ids[i]));
      worst = std::max(worst, std::fabs(static_cast<double>(route.weights[i]) - v::k_route_w[i]));
    }
  std::printf("  router: %d tokens, max weight error %.5f\n", v::kTokens, worst);
  require(worst < 0.02, "router weights: " + std::to_string(worst));
}

DGPP_TEST(mistral4_moe_block_is_the_engines_nvfp4_oracle) {
  // The existing MoE oracle (the routed chain the device layer is tested
  // against) on this layer's containers: w1 / w3 / w2 as gate / up / down,
  // the shared expert in the chain, the stored weight_global_scale as the
  // divisor. No new MoE operator.
  const dgpp::GlmMoeConfig mc = config().moe_config(v::kInter);
  dgpp::GlmMoeHostWeights w;
  w.router_gate.assign(v::k_gate, v::k_gate + static_cast<size_t>(v::kExperts) * v::kHidden);
  w.nvfp4 = true;
  w.shared_nvfp4 = true;
  w.fp4_group = 16;
  w.fp4_payloads.assign(std::begin(v::k_fp4_payloads), std::end(v::k_fp4_payloads));
  w.fp4_scales.assign(std::begin(v::k_fp4_scales), std::end(v::k_fp4_scales));
  w.fp4_globals.assign(std::begin(v::k_fp4_globals), std::end(v::k_fp4_globals));
  require(w.fp4_globals.size() == static_cast<size_t>(v::kExperts + 1) * 3,
          "one global per matrix");
  std::vector<uint16_t> out;
  dgpp::glm_moe_ref_forward(v::k_hidden, w, mc, v::kTokens, out);
  require(out.size() == static_cast<size_t>(v::kTokens) * v::kHidden, "output rows");
  const double e = rel_error(out.data(), v::k_moe_out, out.size());
  std::printf("  moe block: out error %.4f\n", e);
  require(e < kOutputBound, "moe block: " + std::to_string(e));
  // The up and gate projections exchanged (w3 as the gate) is a different function.
  dgpp::GlmMoeHostWeights swapped = w;
  const size_t pbytes = static_cast<size_t>(v::kInter) * v::kHidden / 2,
               sbytes = static_cast<size_t>(v::kInter) * v::kHidden / 16;
  for (int e3 = 0; e3 <= v::kExperts; ++e3) {
    std::swap_ranges(swapped.fp4_payloads.begin() + e3 * 3 * pbytes,
                     swapped.fp4_payloads.begin() + (e3 * 3 + 1) * pbytes,
                     swapped.fp4_payloads.begin() + (e3 * 3 + 1) * pbytes);
    std::swap_ranges(swapped.fp4_scales.begin() + e3 * 3 * sbytes,
                     swapped.fp4_scales.begin() + (e3 * 3 + 1) * sbytes,
                     swapped.fp4_scales.begin() + (e3 * 3 + 1) * sbytes);
    std::swap(swapped.fp4_globals[size_t(e3) * 3], swapped.fp4_globals[size_t(e3) * 3 + 1]);
  }
  std::vector<uint16_t> out2;
  dgpp::glm_moe_ref_forward(v::k_hidden, swapped, mc, v::kTokens, out2);
  const double e2 = rel_error(out2.data(), v::k_moe_out, out2.size());
  std::printf("  moe block with gate and up exchanged: out error %.4f\n", e2);
  require(e2 > 4 * kOutputBound, "gate / up order is not told apart: " + std::to_string(e2));
}
